### ISSUE TITLE
Import and Visualization of "SceneObjects"

### ISSUE THREAD

**Issue by ThomasOrtner** [vrvis/PRo3D#13]
SceneObjects are 3D objects that do not have a semantic background, such as being a surface or a scalebar. When we want to place for instance a rover model we need to import the respective 3D model via the Top Menu. Ideally, the File Open Dialog should show all formats offered by the Assimp loader, but I suppose we can limit that to *.dae and *.obj for now. Scene Objects need a list view to select, manage and delete them. Further, a special interaction is needed to place them onto the surface and further interactions for transformation. Scientists prefer accurate transformations via meaningful numeric controls, i.e. translation along north and east, and rotation as azimuth. As an extension, we can think of reactivating maya-like controllers.

- [x] loading the model dae and obj
- [x] integration into domain model
- [x] list gui and interaction icons
- [ ] gui properties
- [x] integration translation app
- [x] picking placement

[Requirement P3D-E004](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=68:68)

**Comment by haraldsteinlechner** [comment]
looks like maya controller rework revive :)

**Comment by ThomasOrtner** [comment]
Not necessarily. Most scientists prefer the more accurate numeric controls. I will update the issue accordingly ;)

**Comment by LauraFritz14** [comment]
**Branch**: develop/features/sceneObjects
**Testdaten**: file://euclid.vrvis.lan/InOut/PRo3D/Job-MCZ-Pano-Sol3_opc.zip + Roverdaten von Chris
**Laden von Scene Objects**: menu -> "Scene Objects" -> "Import (*.obj ord *.dae)
**UI**:
Das geladene Scene Object (SO) ist in der Liste im "SceneObjects" Tab zu sehen. Unter dem Namen in der Liste gibt es 4 Icons: FlyTo, OpenFolder, (in)Visible und Remove. Die funktionieren auch wenn das SO nicht selektiert ist. Um das SO zu selektieren klickt man auf den Namen in der Liste (der Name wird dann grün). Für das selektierte SO kann man die Transformations im "Transformation" accordion verwenden. 
**Picking Interaction**: mit "PlaceSceneObject" kann das selektierte SO mit CTRL+LMB auf einen beliebigen Punkt der Surface gesetzt werden.
![img](https://user-images.githubusercontent.com/24911426/110933324-e5139e80-832c-11eb-9bf4-1f9b73fadd76.png)

**Comment by chris-traxler** [comment]
**Test Report**

The test was successful. I imported DAE and OBJ rover models and positioned them with _PlaceSceneObject_. I also set translations and yaw numerically in the GUI. I tried out all context menu functions for scene objects. There is one bug and one usability issue to report:

- [ ] Bug: The context menu function "Fly to" (home icon) does not adjust the view to see the scene object in the center. It seems to assume an arbitrary viewpoint sometimes bringing the entire scene into view. 
- [ ] Usability Issue: When first using _PlaceSceneObject_ and then adjusting translations numerically in the GUI, the scene object snaps back to the world origin. This is irritating, because you would assume that translations are relative to the new object origin defined by _PlaceSceneObject_ .

**Comment by LauraFritz14** [comment]
Transformation + "Fly to" bugs are fixed. 
"Perseverence.dae" has a wrong bounding box:
![bbs](https://user-images.githubusercontent.com/24911426/112819262-aef05180-9084-11eb-8f8c-0102193748de.png)

**Comment by LauraFritz14** [comment]
![so_priority](https://user-images.githubusercontent.com/24911426/114000360-385d0c00-985b-11eb-8ce1-9c44825e3ab4.png)
highest priority for scene objects

**Comment by chris-traxler** [comment]
All features successfully tested. All reported bugs fixed.
