### ISSUE TITLE
Coordinate System Comparison

### ISSUE THREAD

**Issue by chris-traxler** [vrvis/PRo3D#43]
Numerically compare dimensions along all coordinate axes between two models or surfaces (i.e. the distance between intersection points of all axes with the surface). Calculate also the rotational axes deviations. Suitable for spheroid surfaces where the origin lies inside. Task separation:

- [x] Calculate axes distances of two selected surfaces and their differences.
- [x] Calculate rotational deviations of two selected surfaces. 
- [x] Display differences in GUI. 
- [x] Export to JSON.

[Requirement P3D-P003](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=36:36)

**Comment by RebeccaNowak** [comment]
The origin of surfaces after loading is not in the origin of the coordinate system; the coordinate system's origin is used as pivot point when rotating surfaces; this leads to unexpected translations when using Transformations (currently only Yaw) in the GUI; this behaviour will lead to imprecisions when comparing models that are expected to have their origin in the same place, because every rotation moves their origin around. We need to investigate this further.
